// import fs from "fs",// import path from "path",
// const dataDir = path.join(process.cwd(), "/data/movie_names.txt")
// const ddir = fs.readdirSync(postsDir)
// console.log(dataDir)

// export default async function getRMovie(){
	
// 	const file = fs.readFileSync(dataDir)
	
// 	const movies = file.toString().split(/\r\n/)
	
// 	return {
// 		movies
// 	}
// }

const dataMovies = [
	'Baazigar',
	'Wake Up Sid',
	'Tubelight',
	'Delhi Belly',
	'Prem Ratan Dhan Payo',
	'Rockstar',
	'Piku',
	'Socha Na Tha',
	'Dil Se',
	'Devdas',
	'Hum Dil De Chuke Sanam',
	'Nenokkadine',
	'Jolly LLB 2',
	'Ghilli',
	'Raanjhanaa',
	'Hungama',
	'Rangeela',
	'Khakee',
	'Kaththi',
	'Rocket Singh',
	'Dear Zindagi',
	'Jaane Tu... Ya Jaane Na',
	'Madaari',
	'Mankatha',
	'Ghajini',
	'Yuva',
	'Baghban',
	'Badlapur',
	'Thappakki',
	'Chachi 420',
	'Guzaarish',
	'Kaminey',
	'Kabhi Khushi Kabhie Gham...',
	'Shivaji',
	'Maine Pyar Kiya',
	'Once Upon a Time in Mumbaai',
	'zero',
	'Life in a Metro',
	'Ghulam',
	'Ishqiya',
	'Khaleja',
	'Golmaal',
	'Jolly LLB',
	'Mardaani',
	'Psycho Raman',
	'Lootera',
	'Parineeta',
	'Pyaar Ka Punchnama 2',
	'Shaitan',
	'Band Baaja Baaraat',
	'Srimanthudu',
	'Dookudu',
	'Holiday',
	'Shanghai',
	'Tere Bin Laden',
	'Te3n',
	'Bhool Bhulaiyaa',
	'Uppi 2',
	'Namastey London',
	'Gunda',
	'D-Day',
	'Nanban',
	'Paa',
	'Talaash',
	'Fanna',
	'Nh10',
	'i',
	'Dedh Ishqiya',
	'Yanni Arindhaai',
	'Wazeer',
	'Dasavatharam',
	'Gabbar is Back',
	'Sanam Teri Kasam',
	'Dhobi Ghat',
	'Kaabil',
	'Luck by Chance',
	'Race Gurram',
	'Koi... Mil Gaya',
	'Rab Ne Bana Di Jodi',
	'Hum Tum',
	'Pokkiri',
	'Tere Naam',
	'Mohabbatein',
	'Pardes',
	'Rustom',
	'Karthik Calling Karthik',
	'2 States',
	'Fashion',
	'Fan',
	"Radhe",
"Flight",
"Mumbai Saga",
"Vijay The Master",
"Chakra Ka Rakshak",
"The Power",
"Khuda Hafiz",
"Bagi 3",
"Malang",
"Dabang 3",
"Mardani 2",
"Marjaavaan",
"Sahoo",
"Bharat",
"Satyamev Jayte",
"Drive",
"War",
"Raid",
"Badshahoo",
"Raees",
"Razi",
"Wazeer",
"Akira",
"Article 15",
"Tanhaji",
"Kesari",
"Parmanu",
"Batla House",
"Spider",
"Tiger Jinda Hai",
"Madras Cafe",
"Detective Byomkesh Bakshy",
"Dangal",
"Bothers", 
"Bahubali 1",
"Bahubali 2",
"Baby",
"Bajiro Mastani",
"Agent Vinod",
"Baghi",
"Jay ho",
"Singham Return",
"Coolie No1",
"Roohi",
"Chhichhore",
"Anadadhund",
"Angrezi Medium",
"Sanju",
"Tamasha",
"Paglait",
"Bhoot",
"Bala",
"Ae Dil Hai Mushkil",
"Stree",
"Sanam Teri Kasam",
"Kabeer Singh",
"Pad Man",
"Sultan",
"Rabata",
"Hero",
"Super 30",
"Piku",
"Dilwale 2",
"Bajrangi Baijaan",
"Baghi2",
"PK",
"Ranzanaa",
"Street Dancer",
"M. S. Dhoni",
"Aashiqui 2",
"Malang",
"Ye Jawaani Hai Deewani",
"Toilet Ek Prem Katha",
"Total Dhamal",
"Housefull 4",
"Three Idiots",
"Bhool Bhuliya",
"Hungama",
"Entertainment",
"Welcome",
"Welcome Back",
"Devdas",
"Pink",
"Dear Zindgi",
"Mery Kom",
"Saina",
"Jodha Akbar",
"Queen",
"Lagaan",
"Hichki",
"English vinglish",
"Highway",
"Thappad",
"Panga",
"Sui Dhaga",
"Koi Mil Gaya",
"Rustam",
"Kabhi Khushi Kabhi Gum",
"Hum Apke Hai Kun",
"Sajan",
"Dil",
"Judwaa 2",
"Khiladi",
"Zero",
"Chhalang",
"Barfi",
"Dangal",
"Chak De India",
"Azahar","Toofaan",
"Jersey","Maidaan",
"Raone","Ghajni",
"Veer",
"Veer Zaara",
"Mission Mangal",
"Half GirlFriend",
"Jagga jasoos",
]
export const rmovies = [
	"Flight",
	"Mumbai Saga",
	"Vijay The Master",
	"Chakra Ka Rakshak",
	"The Power",
	"Khuda Hafiz",
	"Bagi 3",
	"Malang",
	"Dabang 3",
	"Mardani 2",
	"Marjaavaan",
	"Sahoo",
	"Bharat",
	"Satyamev Jayte",
	"Drive",
	"War",
	"Raid",
	"Badshahoo",
	"Raees",
	"Razi",
	"Wazeer",
	"Akira",
	"Article 15",
	"Tanhaji",
	"Kesari",
	"Parmanu",
	"Batla House",
	"Spider",
	"Tiger Jinda Hai",
	"Madras Cafe",
	"Detective Byomkesh Bakshy",
	"Dangal",
	"Bothers", 
	"Bahubali 1",
	"Bahubali 2",
	"Baby",
	"Bajiro Mastani",
	"Agent Vinod",
	"Baghi",
	"Jay ho",
	"Singham Return",
	"Coolie No1",
	"Roohi",
	"Chhichhore",
	"Anadadhund",
	"Angrezi Medium",
	"Sanju",
	"Tamasha",
	"Paglait",
	"Bhoot",
	"Bala",
	"Stree",
	"Sanam Teri Kasam",
	"Kabeer Singh",
	"Pad Man",
	"Sultan",
	"Rabata",
	"Hero",
	"Super 30",
	"Piku",
	"Dilwale 2",
	"Bajrangi Baijaan",
	"Baghi2",
	"PK",
	"Ranzanaa",
	"Street Dancer",
	"M. S. Dhoni",
	"Aashiqui 2",
	"Malang",
	"Ye Jawaani Hai Deewani",
	"Toilet Ek Prem Katha",
	"Total Dhamal",
	"Housefull 4",
	"Three Idiots",
	"Bhool Bhuliya",
	"Hungama",
	"Entertainment",
	"Welcome",
	"Welcome Back",
	"Devdas",
	"Pink",
	"Dear Zindgi",
	"Mery Kom",
	"Saina",
	"Jodha Akbar",
	"Queen",
	"Lagaan",
	"Hichki",
	"English vinglish",
	"Highway",
	"Thappad",
	"Panga",
	"Sui Dhaga",
	"Koi Mil Gaya",
	"Rustam",
	"Kabhi Khushi Kabhi Gum",
	"Hum Apke Hai Kun",
	"Sajan",
	"Dil",
	"Judwaa 2",
	"Khiladi",
	"Zero",
	"Chhalang",
	"Barfi",
	"Dangal",
	"Chak De India",
	"Azahar","Toofaan",
	"Jersey","Maidaan",
	"Raone","Ghajni",
	"Veer",
	"Veer Zaara",
	"Mission Mangal",
	"Half GirlFriend",
	"Jagga jasoos",
	]

export default function getRMovie(all=false, count=5){
	const moviess = dataMovies
	if (all) {
		return moviess
	}
    const len = moviess.length
    const rand = [...Array(count)].map(e=>Math.random()*len|0)
    const movies = rand.map(i => moviess[i])
	return movies
}

export function getRIdMovie() {
	const len = rmovies.length
	const rand = Math.random()*len|0
	return rmovies[rand]
}

